# Use a imagem oficial do Node.js como base
FROM node:18-alpine

# Define o ambiente como produção
ENV NODE_ENV=production

# Define o diretório de trabalho dentro do container
WORKDIR /usr/src/app

# Copia os arquivos necessários para instalar dependências
COPY package*.json ./

# Instala as dependências de produção
RUN npm ci --only=production

# Copia o restante do código para o diretório de trabalho
COPY . .

# Cria um novo usuário não root para rodar o aplicativo
RUN addgroup appgroup && adduser -S appuser -G appgroup

# Define o usuário para rodar o aplicativo
USER appuser

# Exponha a porta que o backend usa
EXPOSE 3000

# Comando para iniciar o servidor
CMD ["npm", "start"]
