# Use uma imagem oficial do Node.js como base
FROM node:18-alpine

# Define o diretório de trabalho dentro do container
WORKDIR /usr/src/app

# Copia o arquivo package.json e package-lock.json
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código para o diretório de trabalho
COPY . .

# Expõe a porta que o backend usa (ajuste para a porta correta, por exemplo, 3000)
EXPOSE 3000

# Comando para iniciar o servidor
CMD ["node", "server.js"]
